# Generated by Django 2.2.16 on 2022-06-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
    ]
